### ISSUE TITLE
Cannot start new game with ExportAgency activated

### ISSUE THREAD

**Issue by ab9rf** [erdelf/ExportAgency#2]
No matter what scenario is chosen, all clicking the "next" button yields is an exception:
```
Exception filling window for RimWorld.Page_SelectScenario: System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
at System.Collections.Generic.List`1<RimWorld.DrugPolicyEntry>.set_Item (int,RimWorld.DrugPolicyEntry) <0x000a9>
at RimWorld.DrugPolicy.set_Item (int,RimWorld.DrugPolicyEntry) <0x00039>
at ExportAgency.ExportAgency.DrugPolicyDatabasePostfix (RimWorld.DrugPolicyDatabase) <0x0019f>
at (wrapper dynamic-method) RimWorld.DrugPolicyDatabase..ctor_Patch1 (object) <0x00075>
at Verse.Game..ctor () <0x003b6>
at RimWorld.Page_SelectScenario.BeginScenarioConfiguration (RimWorld.Scenario,RimWorld.Page) <0x00041>
at RimWorld.Page_SelectScenario.CanDoNext () <0x00053>
at RimWorld.Page.DoBottomButtons (UnityEngine.Rect,string,string,System.Action,bool,bool) <0x00471>
at RimWorld.Page_SelectScenario.DoWindowContents (UnityEngine.Rect) <0x004b8>
at Verse.Window/<WindowOnGUI>c__AnonStorey0.<>m__0 (int) <0x00882>
```

Note that I was using ExportAgency in B19, and I have a handful of things exported from prior versions saved. I have not yet tried removing these to see if doing so resolves the error.

**Comment by erdelf** [comment]
A common error in that position, sadly nothing I can do about it. Try going in the mod options and removing the ones that include modded drugs that you don't have anymore.

**Comment by ab9rf** [comment]
That would make sense; VG hasn't been updated for 1.0 yet and so the references to drugs from VG are dead.

However, I disagree with your contention that you "can do nothing about it"; you really should handle such references without throwing exceptions. Surely it's possible to wrap those calls in try/catch?

**Comment by erdelf** [comment]
if I would, you wouldn't be able to access any of them.. so yeah.

**Comment by ab9rf** [comment]
Your last comment doesn't make any sense to me at all.

**Comment by erdelf** [comment]
you wouldn't be able to access any of your things you saved with this mod.

**Comment by ab9rf** [comment]
Ok, you've convinced me that it's time to figure out how to build RimWorld mods, because I'm absolutely certain that what you've said above is 100% wrong.

I'm not familiar with RimWorld's internals and I have relatively little experience with C#, but there's no reason whatsoever why a try-catch wrapper around the code at https://github.com/erdelf/ExportAgency/blob/f386644278b2f4dc5120af32411770ce6bc10161/Source/ExportAgency/ExportAgency.cs#L169-L174 (the `set_Item` call that is excepting is clearly the implicit call at line 172) would make it so that "you wouldn't be able to access any of your things you saved with this mod". (It would simply prevent accessing the things that can't be loaded because they have stale references.) 

But since you seem adverse to even considering it, I'll just have to fork and do it myself.

**Comment by erdelf** [comment]
Nice try, but that is not the problem.

**Comment by ab9rf** [comment]
Since you wontfix, I'll just close this for you.
